-- Add missing fields to programs table
ALTER TABLE programs ADD COLUMN IF NOT EXISTS instructor VARCHAR(255);
ALTER TABLE programs ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE programs ADD COLUMN IF NOT EXISTS price DECIMAL(10, 2) DEFAULT 0;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS total_seats INTEGER DEFAULT 0;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS available_seats INTEGER DEFAULT 0;
